apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::338978025035:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-15LVCUANRZHG5
      username: system:node:{{EC2PrivateDNSName}}
     - groups:
      - system:masters
      rolearn: arn:aws:iam::338978025035:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-23T13:24:51Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1247"
  uid: c8449082-66af-4517-8a7b-a6b5ed5517d1
